#!/bin/bash

set -e
# Load RVM into a shell session *as a function*
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then

  # First try to load from a user install
  source "$HOME/.rvm/scripts/rvm"

elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then

  \# Then try to load from a root install
  source "/usr/local/rvm/scripts/rvm"

else

  printf "ERROR: An RVM installation was not found.\n"

fi

cd /rails

bundle install
RAILS_ENV=development bundle install
RAILS_ENV=test bundle install
bundle exec rake db:schema:load
bundle exec rake seeds:all
